Add GRIT model
graphnet-team/graphnet pull request #777
Opened 2024-12-17 20:16 UTC by pweigel

### GRIT: "Graph Inductive Biases in Transformers without Message Passing"
This PR includes a new model based on the GRIT transformer. It uses novel methods for encoding graph information for use in sparse multi-head attention blocks. It uses a learned position encoding based on random walk probabilities, which enhances the model's expressivity.

PMLR: https://proceedings.mlr.press/v202/ma23c.html
Paper pre-print: https://arxiv.org/abs/2305.17589

![image](https://github.com/user-attachments/assets/8a8819cf-ab09-4561-a501-eab2c3ebf98f)

Many layers/functions are adapted from the original repository: https://github.com/LiamMa/GRIT/tree/main. The original code uses `graphgym` to set up most of its modules, so I refactored some things to fit into graphnet. Many of the arguments have been relabeled to be more self-explanatory. In principle, other graph attention mechanisms could be used by replacing the GRIT MHA block. 

Since there are a lot of changes, I will quickly summarize the significant new additions and modifications to existing files:

- [src/graphnet/models/components/embedding.py](https://github.com/graphnet-team/graphnet/compare/main...pweigel:graphnet:grit#diff-f0f33604024b7cf450a886a8e94df9afe84760555fdafcc399377994994c92ee): Adds four encoding modules, which apply linear and RRWP encodings to nodes and edges.
- [src/graphnet/models/components/layers.py](https://github.com/graphnet-team/graphnet/compare/main...pweigel:graphnet:grit#diff-4eaa1b7d1c266a2439af0ff264d00ef274a5c7e97d9aa6388c9154e32d919cf1): Adds GRIT sparse multi-head attention, the core of the GRIT model, and the GRIT transformer layer.
- [src/graphnet/models/gnn/grit.py](https://github.com/graphnet-team/graphnet/compare/main...pweigel:graphnet:grit#diff-c3a2c42bf35e7e1f77b16930222ee8032099f2fa5b713f5192aca4066a096de6): Implementation of GRIT as a GNN model.
- [src/graphnet/models/graphs/edges/edges.py](https://github.com/graphnet-team/graphnet/compare/main...pweigel:graphnet:grit#diff-85c6e5df5fe062e8c382f4d5db4ac86526fc97f2b3b5fee85e3c8813dd26924d): Added a variant of the `KNNEdge` (`KNNDistanceEdges`) to include edge values corresponding to the distance between the node pair.
- [src/graphnet/models/graphs/graphs.py](https://github.com/graphnet-team/graphnet/compare/main...pweigel:graphnet:grit#diff-78ce7f838fa1e2ec5a57b5bd1820615dcb869bc3d3cedcc04121e79efdec2b4c): Added a variant of the `KNNGraph` to use the `KNNEdgeDistance` and compute the RRWP values.
- [src/graphnet/models/utils.py](https://github.com/graphnet-team/graphnet/compare/main...pweigel:graphnet:grit#diff-a14c152e62a2cefdb5448d6f2bdc30701e97319ceeb99416d7336fd55d9efe37): Added new utilities needed for the RRWP calculation and other miscellaneous tools used by the GRIT transformer layers.
- [examples/04_training/08_train_grit_model.py](https://github.com/graphnet-team/graphnet/compare/main...pweigel:graphnet:grit#diff-088fd8c5e18678c8be006b270440cd12a24292e2c7133e74cad1d6af2df5bf2e): Example training script using GRIT.

This model has many hyperparameters, but the defaults should provide a good starting point. It should be noted that the GPU memory required to train this model is quite high due to the use of global attention.

2024-12-24 16:19 UTC, pweigel commented
After some experimenting, I've found that no position encoding works quite well (skipping the RRWP encodings) and drastically reduces the GPU memory requirement. I'll add some options that allow users to do this.

2025-01-02 12:26 UTC, RasmusOrsoe commented on src/graphnet/models/utils.py
> +    # rel_pe_idx = torch.stack([rel_pe_row, rel_pe_col], dim=0)
forgot a comment here

2025-01-02 12:26 UTC, RasmusOrsoe commented on src/graphnet/models/utils.py
> +    attr_name_rel: str = "rrwp",  # name: ('rrwp_idx', 'rrwp_val')
forgot a comment here

2025-01-02 12:26 UTC, RasmusOrsoe commented on src/graphnet/models/utils.py
> +    # dest = edge_index[1]
forgot a comment here

2025-01-02 12:27 UTC, RasmusOrsoe commented on src/graphnet/models/utils.py
> +        # _edge_index, _ = remove_self_loops(_edge_index)
forgot a comment here

2025-01-02 12:36 UTC, RasmusOrsoe commented on src/graphnet/models/utils.py
> +    # device = data.edge_index.device
forgot a comment here

2025-01-02 13:35 UTC, RasmusOrsoe commented on src/graphnet/models/components/layers.py
> +            out_dim: Dimension of theo output tensor.
theo -> the

2025-01-02 13:37 UTC, RasmusOrsoe commented on src/graphnet/models/components/layers.py
> +        # Complete attention ccaclculation
ccaclculation -> calculation

2025-01-02 13:46 UTC, RasmusOrsoe commented on src/graphnet/models/components/layers.py
> +            norm: Normalization layer.
Would be informative to mention here that the normalization layer is assumed to be un-instantiated. E.g: 

`norm: Uninstantiated normalization layer. Must be either BatchNorm1d or BatchNorm1d`

2025-01-02 14:07 UTC, RasmusOrsoe commented on src/graphnet/models/graphs/graphs.py
> +    """KNN Graph with relative random walk probabilities."""
Similarly to the other representation, I would suggest expanding the doc string so it's easier to see how this differs from existing representations and how the new fields are accessible. I think there are five new fields in the RRWP case. So here's an example:

"""
A KNN graph representation with Relative Random Walk Probabilities (RRWP).

Identical to KNNGraph but with five additional fields:  

`abs_pe = graph['abs_pe']` # Absolute positional encoding
`rrwp_index = graph['rrwp_index']` # rrwp index (which is used for slicing the vals?)
`rrwp_val = graph['rrwp_val']` # rrwp values
`degree= graph['deg']` # Degree of each node (num. of incoming edges)
`log_degree = graph['log_deg']` # Equal to torch.log10(graph['deg'] + 1)
"""

2025-01-02 14:15 UTC, RasmusOrsoe commented on src/graphnet/models/graphs/graphs.py
> +class KNNGraphNoPE(GraphDefinition):
Considering the very high level of similarity between this and `KNNGraph`, perhaps it would be beneficial to introduce a new argument to `KNNGraph` that would toggle between the vanilla KNNEdges and your new KNNDistanceEdges. For example, one could invent the argument `distance_as_edge_features: bool = False` (defaults to `KNNEdges`) and use `KNNDistanceEdges` if `True`.

2025-01-02 14:20 UTC, RasmusOrsoe commented on src/graphnet/models/components/layers.py
> +            activation: Activation function.
Could mention here that the activation function is assumed to be un-instantiated. E.g.
```
"""
activation:  Reference to uninstantiated activation function. E.g. `torch.nn.LeakyReLU`
"""
```

2025-01-02 14:21 UTC, RasmusOrsoe commented on src/graphnet/models/components/layers.py
> +        attn_dropout: float = 0.0,  # CHECK
Forgot a comment here

2025-01-02 14:24 UTC, RasmusOrsoe commented on src/graphnet/models/components/layers.py
> +        else:  # TODO: Maybe just set this to nn.Identity. -PW
I think preferred to raise the error if the user passes a non-compatible layer instead of passing warnings and defaulting to identity

2025-01-02 14:31 UTC, RasmusOrsoe commented on src/graphnet/models/components/layers.py
> +        log_deg = get_log_deg(data)
Was there some particular reason why you needed the utility function to grab or calculate this quantity?

Naively I would've thought the degree could've been calculated directly in the forward pass like  so: 

```python
from torch_geometric.utils import degree
log_deg = torch.log10(degree(data.edge_index[0]) + 1)
```

2025-01-02 14:33 UTC, RasmusOrsoe commented on src/graphnet/models/components/layers.py
> +        activation: nn.Module = nn.ReLU,
Could mention here that the activation function is assumed to be un-instantiated. E.g.
```
"""
activation:  Reference to uninstantiated activation function. E.g. `torch.nn.LeakyReLU`
"""
```

2025-01-02 14:34 UTC, RasmusOrsoe commented on src/graphnet/models/components/layers.py
> +            activation: Activation function.
Could mention here that the activation function is assumed to be un-instantiated. E.g.
```
"""
activation:  Reference to uninstantiated activation function. E.g. `torch.nn.LeakyReLU`
"""
```

2025-01-02 14:35 UTC, RasmusOrsoe commented on src/graphnet/models/gnn/grit.py
> +        activation: nn.Module = nn.ReLU,
Could mention here that the activation function is assumed to be un-instantiated. E.g.
```
"""
activation:  Reference to uninstantiated activation function. E.g. `torch.nn.LeakyReLU`
"""
```

2025-01-02 14:35 UTC, RasmusOrsoe commented on src/graphnet/models/gnn/grit.py
> +        norm: nn.Module = nn.BatchNorm1d,
Would be informative to mention here that the normalization layer is assumed to be un-instantiated. E.g: 

`norm: Uninstantiated normalization layer. Must be either BatchNorm1d or BatchNorm1d`

2025-01-02 14:36 UTC, RasmusOrsoe commented on src/graphnet/models/components/layers.py
> +            activation: Activation function.
Could mention here that the activation function is assumed to be un-instantiated. E.g.
```
"""
activation:  Reference to uninstantiated activation function. E.g. `torch.nn.LeakyReLU`
"""
```

2025-01-02 15:06 UTC, RasmusOrsoe requested changes
Hi @pweigel, thank you for this very clean contribution! 🎸 

I have added superficial comments, mostly about commented-out code and doc strings.

Have you, by chance, tested these different initial representations and their impact on the performance of the GRIT model in a neutrino telescope setting? The original authors appear to favor RRWP over RWSE (I presume they conclude RRPW > RWSE > NoPE), but that may be very problem-dependent.

2025-01-10 17:34 UTC, pweigel commented
Hey @RasmusOrsoe, thanks for taking a look. I think I've made all of the requested changes (and fixed a few other minor things). I haven't had the chance to benchmark the different encodings yet, but I plan to. The RRWP encodings are a bit memory-hungry, so I haven't had the chance to fully train a model beyond some tests to show that it works. Without the encodings, I've trained some models that look very good.

At some point in the near future, we should consider a better method of adding the different attributes (`graph.encoding`) in a modular fashion that doesn't require a new graph object. It could even be added as a part of `GraphDefinition`, where you pass some `pos_encoding=MyGraphPosEncoding()` and it uses the values/indices from the edge and node definitions to add the new attributes. It might be beyond the scope of this PR, but it would definitely be an enhancement.

2025-01-16 12:01 UTC, RasmusOrsoe commented
> Hey @RasmusOrsoe, thanks for taking a look. I think I've made all of the requested changes (and fixed a few other minor things). I haven't had the chance to benchmark the different encodings yet, but I plan to. The RRWP encodings are a bit memory-hungry, so I haven't had the chance to fully train a model beyond some tests to show that it works. Without the encodings, I've trained some models that look very good.
> 
> At some point in the near future, we should consider a better method of adding the different attributes (`graph.encoding`) in a modular fashion that doesn't require a new graph object. It could even be added as a part of `GraphDefinition`, where you pass some `pos_encoding=MyGraphPosEncoding()` and it uses the values/indices from the edge and node definitions to add the new attributes. It might be beyond the scope of this PR, but it would definitely be an enhancement.

Thanks! I think your idea of adding a positional encoding as a separate module, and storing its values in a dedicated field in the graph structures, is good! I also think this is the intended usage in PyG (see [here](https://pytorch-geometric.readthedocs.io/en/latest/get_started/introduction.html#data-handling-of-graphs)). We've not utilized this in the past because the distinction between having the position as a node feature or as a separately accessible graph feature didn't matter much for the GNN applications we've had so far. I think your use-case is a good example of how it can be beneficial!

It looks like the GitHub rollout to the new ubuntu version has affected your PR checks. @Aske-Rosted has solved this in the main branch (see #779). 

Could you merge the main branch into yours, so the checks pass? The checks should pass after that 💪

2025-01-21 11:29 UTC, RasmusOrsoe approved these changes
🚀

2025-01-21 13:47 UTC, merged